WIP  Add dialyzer
resuelve/resuelve-auth-plug pull request #32
Opened 2022-04-25 20:17 UTC by HugoTranquilino

¿Qué es lo que hice? 

- Añadí dialyzer al proyecto.
- se comienzan a resolver algunos errores detectados por dialyzer.

2022-05-04 15:07 UTC, ZeroDragon approved these changes, later dismissed

2022-05-04 20:58 UTC, ZeroDragon approved these changes, later dismissed

2022-05-05 21:45 UTC, narbigcito submitted a review, later dismissed

2022-05-05 22:29 UTC, RoverWire submitted a review, later dismissed

2022-05-05 22:57 UTC, ivanhoe submitted a review, later dismissed

2022-05-05 22:59 UTC, erickgnavar commented on .credo.exs
> +      }
¿estos ajustes son parte de la implementación de dialyzer? En este proyecto no tenemos un check para formateo aún pero me parece que se rompería con estos ajustes

2022-05-05 22:59 UTC, erickgnavar commented on lib/token_data.ex
> +  defp split(_token), do: []
¿en qué casos se mandaría algo que no fuera un string?

2022-05-06 05:52 UTC, capipo commented on .credo.exs
> +      }
Debido a que actualizamos elixir en `.tool-versions`, tuvimos que actualizar credo, y solo regeneramos este archivo de configuración `mix credo gen.config`

2022-05-06 05:53 UTC, capipo commented on lib/token_data.ex
> +  defp split(_token), do: []
Estaba tentado a quitar este caso, pero como en el código original se le dio soporte a recibir algo que no es string, por eso dejé el soporte.
Pero si "insistes" lo quitaré XD

2022-05-06 06:06 UTC, ZeroDragon commented on lib/token_data.ex
> +  defp split(_token), do: []
Hay que validar si en algún lugar se usa para retirar el soporte legacy a algo en desuso ... Por lo pronto yo voto por dejarlo y revisar en una siguiente versión el eliminarlo

2022-05-06 06:06 UTC, capipo commented on lib/token_data.ex
> +  defp split(_token), do: []
f904ca20869797aec269a6ea0301acaa76dc3753

2022-05-06 06:09 UTC, capipo commented on lib/token_data.ex
> +  defp split(_token), do: []
@ZeroDragon va pa atras entonces :disappointed:?

2022-05-06 12:44 UTC, ZeroDragon commented on lib/token_data.ex
> +  defp split(_token), do: []
Mi voto es dejar el soporte (no borrarlo) sobre todo porque por algo existe

2022-05-06 15:22 UTC, erickgnavar commented on lib/token_data.ex
> +  defp split(_token), do: []
Solo quería dejar en claro que mi comentario inicial era una duda, no era una indicación de que se tenga que hacer algún cambio sí o sí. Ahora respecto al cambio como tal, si ya estaba funcionando así lo mas sano es dejarlo como tal para no agregar cambios de funcionamiento a un PR que solo debe estar relacionado con `dyalizer`

2022-05-06 15:39 UTC, ZeroDragon commented on lib/token_data.ex
> +  defp split(_token), do: []
Si, creo que me expluqué mal. La idea es dejar (mantener) el soporte existente en este PR, tal cual como estaba originalmente y en un PR consecutivo evaluar si lo quitamos o no xD

2022-05-09 16:39 UTC, capipo commented on lib/token_data.ex
> +  defp split(_token), do: []
Ok, commit dropped ~f904ca20869797aec269a6ea0301acaa76dc3753~

2022-05-09 17:39 UTC, ZeroDragon commented on lib/token_data.ex
> +  defp split(_token), do: []
zaz

2022-05-09 17:51 UTC, erickgnavar submitted a review, later dismissed
![seal-of-approval](https://user-images.githubusercontent.com/862022/167468249-a7486e6b-27e5-42e3-bc88-3d44540a1f23.jpeg)

2022-05-10 22:03 UTC, ivanhoe submitted a review, later dismissed

2022-05-13 11:29 UTC, poncho requested changes

2022-05-13 11:29 UTC, poncho commented on .tool-versions
> +erlang 23.0
Este archivo no debería estar versionado

2022-05-13 11:29 UTC, poncho commented on lib/helpers/token_helper.ex
> +    |> if(do: {:error, :expired}, else: {:ok, data})
¿Por qué cambiar el case por un if de una sola línea?
No cambia la lógica y le quita legibilidad.

2022-05-16 16:48 UTC, HugoTranquilino commented on lib/helpers/token_helper.ex
> +    |> if(do: {:error, :expired}, else: {:ok, data})
nos pareció mas limpio dejarlo de esta manera, pero si consideras **revertirlo**, lo hacemos no hay problema

2022-05-16 16:53 UTC, HugoTranquilino commented on .tool-versions
> +erlang 23.0
pero fue necesario actualizar la versión de elixir y Erlang para el correcto funcionamiento de dialyzer, es por ello que se versiono

2022-05-16 18:06 UTC, poncho commented on .tool-versions
> +erlang 23.0
Si el proyecto requiere mínimo esas versiones se debe de especificarse en el mix.exs del proyecto, no en el .tool-versions de asdf

2022-05-17 00:20 UTC, capipo commented on .tool-versions
> +erlang 23.0
Realmente estas versiones son requeridas para los test de dialyzer y credo, no necesariamente cuando se usa como dependencia, pero ahora que lo mencionas debo admitir que no se que implicaciones tenga que `mix.env` difiera de `.tool-versions`.

Supongo que la mejor práctica es que coincidan

2022-05-17 00:25 UTC, capipo commented on lib/helpers/token_helper.ex
> +    |> if(do: {:error, :expired}, else: {:ok, data})
Prefiero usar `if` cuando la condición es binaria

2022-05-17 00:50 UTC, capipo commented on lib/helpers/token_helper.ex
> +    |> if(do: {:error, :expired}, else: {:ok, data})
A mi en lo personal me parece que estamos forzando el uso de pipe, tal vez sea mejor algo como esto:

```elixir
if(Calendar.diff(DateTime.utc_now(), time) > limit_time,
   do: {:error, :expired}, else: {:ok, data})
```

2022-05-17 13:53 UTC, poncho commented on .tool-versions
> +erlang 23.0
La versión de elixir del `mix.exs` indica con que versión se debe compilar el proyecto. El .tool-versions no sirve de nada si, por ejemplo, alguien no usa asdf

2022-05-17 13:59 UTC, poncho commented on lib/helpers/token_helper.ex
> +    |> if(do: {:error, :expired}, else: {:ok, data})
No es de que yo prefiera o alguien prefiera alguna manera, lo único que comenté es que el cambio no hace nada ni ayuda a hacer el proceso más legible, es todo.

Si no les gusta usar pipes no los usen, sólo explico que pipear a un if de una sola línea no ayuda a leer mejor el código. Muchas veces tratando de escribir menos código o líneas no ayudamos a hacerlo más claro.

La solución que pones del if se ve bien.

2022-05-17 21:01 UTC, RoverWire submitted a review, later dismissed

2022-05-18 07:18 UTC, capipo commented on lib/helpers/token_helper.ex
> +    |> if(do: {:error, :expired}, else: {:ok, data})
d0e8d4af37c0e3a0e13fcbe21647cc4832968e99

2022-05-18 07:19 UTC, capipo commented on .tool-versions
> +erlang 23.0
f4be1790189945495c8c2f6e5ee1312f6db65115

2022-05-18 11:17 UTC, poncho commented on lib/helpers/token_helper.ex
> +    |> if(do: {:error, :expired}, else: {:ok, data})
Proyectos anteriores podrían usar versiones anteriores de la librería

2022-05-18 11:17 UTC, poncho commented on .tool-versions
> +erlang 23.0
Proyectos anteriores podrían usar versiones anteriores de la librería

2022-05-18 11:18 UTC, poncho approved these changes
🦭

2022-05-18 13:57 UTC, merged